# -*- coding: utf-8 -*-
"""Text Preprocessing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_oAYNNHJIjfu8svfNu3dn3ff7RERujBx
"""

!pip install nltk

paragraph="""Narendra Damodardas Modi[a] (born 17 September 1950) is an Indian politician who has served as the prime minister of India since 2014. Modi was the chief minister of Gujarat from 2001 to 2014 and is the member of parliament (MP) for Varanasi. He is a member of the Bharatiya Janata Party (BJP) and of the Rashtriya Swayamsevak Sangh (RSS), a right-wing Hindutva paramilitary volunteer organisation. He is the longest-serving prime minister outside the Indian National Congress.

Modi was born and raised in Vadnagar, Bombay State (present-day Gujarat), where he completed his secondary education. He was introduced to the RSS at the age of eight, becoming a full-time worker for the organisation in Gujarat in 1971. The RSS assigned him to the BJP in 1985, and he rose through the party hierarchy, becoming general secretary in 1998.[b] In 2001, Modi was appointed chief minister of Gujarat and elected to the legislative assembly soon after. His administration is considered complicit in the 2002 Gujarat riots[c] and has been criticised for its management of the crisis. According to official records, a little over 1,000 people were killed, three-quarters of whom were Muslim; independent sources estimated 2,000 deaths, mostly Muslim.[4] A Special Investigation Team appointed by the Supreme Court of India in 2012 found no evidence to initiate prosecution proceedings against him.[d] While his policies as chief minister were credited for encouraging economic growth, his administration was criticised for failing to significantly improve health, poverty and education indices in the state.[e]"""

paragraph

import nltk
from nltk.stem import PorterStemmer #for stemming
from nltk.corpus import stopwords

# tokenization- converts paragraph-sentence-words
nltk.download('punkt')
nltk.download('punkt_tab')
sentences=nltk.sent_tokenize(paragraph) #convert para into sentences

sentences

type(sentences)

stemmer=PorterStemmer() #give base word

stemmer.stem("history")

stemmer.stem("historical")

from nltk.stem import WordNetLemmatizer #for lemmatization

lemmatizer=WordNetLemmatizer() #for meaningful word

nltk.download('wordnet')

lemmatizer.lemmatize("history")

lemmatizer.lemmatize("historical")

len(sentences)

import re

corpus=[]
for i in range(len(sentences)):
  review=re.sub("[^a-zA-Z]"," ",sentences[i])
  review=review.lower()
  corpus.append(review)

corpus

nltk.download('stopwords')

stopwords.words("english")

## stemming
for i in corpus:
  words=nltk.word_tokenize(i)
  for word in words:
    if word not in set(stopwords.words("english")):
      print(stemmer.stem(word))

## lemmatization
for i in corpus:
  words=nltk.word_tokenize(i)
  for word in words:
    if word not in set(stopwords.words("english")):
      print(lemmatizer.lemmatize(word))

## apply stopwords. lemmatize
import re
corpus=[]
for i in range(len(sentences)):
  review=re.sub("[^a-zA-Z]"," ",sentences[i])
  review=review.lower()
  review=review.split()
  review=[lemmatizer.lemmatize(word) for word in review if not word in set(stopwords.words("english"))]
  review=" ".join(review)
  corpus.append(review)

## BOW
from sklearn.feature_extraction.text import CountVectorizer
cv= CountVectorizer(binary=True,ngram_range=(2,3))

X=cv.fit_transform(corpus)
cv.vocabulary_

corpus[0]

X[0].toarray()

## TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer
# cv= TfidfVectorizer()
cv= TfidfVectorizer(ngram_range=(1,1),max_features=3)
X=cv.fit_transform(corpus)

corpus[0]

X[0].toarray()